#!/bin/bash

export GCRM_MACHINE_TYPE=GPU  # CPU GPU
export GCRM_ZONE=europe-west2-c  # europe-west2-c us-central1-b europe-west4-a

export GCRM_SPECIAL_MACHINE_IMAGE_FAMILY=pytorch-1-4-cu100  # can be left empty
